### ISSUE TITLE
Error when running trust demo file: tlsv1 alert unknown ca

### ISSUE THREAD

**Issue by MidrarAdham** [PortlandStatePowerLab/doe-egot-system#8]
## Description:

Running the trust_demo script from the home directory gives the following error message:
```
terminate called after throwing an instance of 'boost::wrapexcept<boost::system::system_error>'
what():  handshake: tlsv1 alert unknown ca
Aborted (core dumped)
```
## Command used to run the trust_demo script:

From home directory, /home/doe-egot-system, I ran the following command:
```
./build/bin/trust_demo
```
## When was the repo cloned:

Yesterday, Nov 7, at 6 p.m.

**Comment by Tylores** [comment]
File pathing was fixed with absolute paths.
